Resources:
  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.configTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  PageConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.pageConfigTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  PageConfigTableArn:
    Value:
        Fn::GetAtt:
        - PageConfigTable
        - Arn
    Export:
      Name: ${self:custom.stage}-PageConfigTableArn